<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="MAIN" Id="{b8de5909-2768-46d4-b7e1-95ca8e910a66}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
	messah: WSTRING := "Hello World";
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>